spring:
  # Templates reloading during development
  thymeleaf:
    prefix: file:src/main/resources/templates/
    cache: false

  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://localhost:3306/blog?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1111

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: create
#    ddl-auto: create # SessionFactory가 시작될 때 데이터베이스 drop을 실행하고 생성된 DDL을 실행한다



logging:
  level:
    com.kang.blog.*: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

